### ISSUE TITLE
YAML for M335

### ISSUE THREAD

**Issue by hathawayj** [dylanjm/Rtemplates#2]
I would like the M335 YAML to be as shown below.
```
   ---  
    title: "Something fascinating"  
    author: "Your Name"  
    date: "`r format(Sys.time(), '%B %d, %Y')`"
    output:  
      html_document:  
        keep_md: true
        toc: true
        toc_float: true
        code_folding: hide
    ---  
```
