### ISSUE TITLE
Can we make a presentation RMD as well

### ISSUE THREAD

**Issue by hathawayj** [dylanjm/Rtemplates#5]
```
---
title: "GREAT TITLE"
author: "YOUR NAME"
output: 
  revealjs::revealjs_presentation:
      lib_dir: externals
      keep_md: true
      incremental: true
      theme: black
      highlight: espresso
      center: true
      code_folding: hide
      reveal_options:
        previewLinks: true
        mouseWheel: true
        slideNumber: true
        maxScale: 3
        margin: 0
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```
```
